"""Add recommendation_events table

Revision ID: 19904cac844d
Revises: 4ce657b3f0cb
Create Date: 2026-09-12 18:38:29.295448

"""
from alembic import op
import sqlalchemy as sa


revision = '19904cac844d'
down_revision = '4ce657b3f0cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_type', sa.Enum('EAT_OUT', 'COOK', name='recommendationtype'), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_events_user_id'), 'recommendation_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_events_user_id'), table_name='recommendation_events')
    op.drop_table('recommendation_events')
    # ### end Alembic commands ###
