"""Initial schema

Revision ID: 4ce657b3f0cb
Revises: 
Create Date: 2026-08-30 02:45:28.958331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '4ce657b3f0cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_nutrition',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('menu_item', sa.String(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('carb', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('cal', sa.Float(), nullable=True),
    sa.Column('attribute_tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('last_fetched', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_nutrition_restaurant_id'), 'restaurant_nutrition', ['restaurant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('day_start_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('daily_targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('carb', sa.Float(), nullable=False),
    sa.Column('fat', sa.Float(), nullable=False),
    sa.Column('cal', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_targets_user_id'), 'daily_targets', ['user_id'], unique=True)
    op.create_table('food_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('LOGGED', 'RECOMMENDED', name='foodlogsource'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('carb', sa.Float(), nullable=False),
    sa.Column('fat', sa.Float(), nullable=False),
    sa.Column('cal', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('reverted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_logs_timestamp'), 'food_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_food_logs_user_id'), 'food_logs', ['user_id'], unique=False)
    op.create_table('pantry_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('carb', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('cal', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pantry_items_barcode'), 'pantry_items', ['barcode'], unique=False)
    op.create_index(op.f('ix_pantry_items_user_id'), 'pantry_items', ['user_id'], unique=False)
    op.create_table('preference_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preference_summaries_user_id'), 'preference_summaries', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preference_summaries_user_id'), table_name='preference_summaries')
    op.drop_table('preference_summaries')
    op.drop_index(op.f('ix_pantry_items_user_id'), table_name='pantry_items')
    op.drop_index(op.f('ix_pantry_items_barcode'), table_name='pantry_items')
    op.drop_table('pantry_items')
    op.drop_index(op.f('ix_food_logs_user_id'), table_name='food_logs')
    op.drop_index(op.f('ix_food_logs_timestamp'), table_name='food_logs')
    op.drop_table('food_logs')
    op.drop_index(op.f('ix_daily_targets_user_id'), table_name='daily_targets')
    op.drop_table('daily_targets')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_restaurant_nutrition_restaurant_id'), table_name='restaurant_nutrition')
    op.drop_table('restaurant_nutrition')
    # ### end Alembic commands ###
